### ISSUE TITLE
Performance statistics

### ISSUE THREAD

**Issue by retr0h** [jmervine/diskcached#2]
I would be curious to see what your performance is like, when you add more items to the cache than you have physical memory, with random r/w to various objects stored in  diskcached.

The reason your stats are in favor of diskcached, is b/c you are fetching from memory, and not the disk.  Once you read a file off disk, our friend Linux will cache it in memory.  Diskcached is faster than memcached, b/c it doesn't need to fetch the object(s) over the wire.

**Comment by jmervine** [comment]
@retr0h I'm revisiting this gem again after a long time. I didn't see your comments until now. I'm going to spend a bit of time updating deps and such and I'll see what I can do about testing with large amounts of data. And you're correct about this being designed for a single server solution.

**Comment by jmervine** [comment]
@retr0h. This has become orphaned. If I need it or something like it again I'll take another look. 😜

**Comment by retr0h** [comment]
> @retr0h. This has become orphaned. If I need it or something like it again I'll take another look. 😜

Oh, I just closed out old issues.
